export { QQAdapter } from "./adapter.js";
export {
  BOT_API_BASE_URL,
  BOT_TOKEN_ENDPOINT,
  DEFAULT_API_BASE_URL,
  DEFAULT_CHUNKED_UPLOAD_THRESHOLD_BYTES,
  DEFAULT_GATEWAY_INTENTS,
  DEFAULT_TOKEN_ENDPOINT,
  QQ_GROUP_JOIN_APPROVAL_STRATEGY_MAX_GROUPS,
  QQ_GROUP_JOIN_APPROVAL_WHITELIST_BATCH_LIMIT,
  QQ_GROUP_JOIN_REQUEST_DEFAULT_LIMIT,
  QQ_GROUP_JOIN_REQUEST_MAX_LIMIT,
  QQ_GROUP_MUTE_MEMBER_BATCH_LIMIT,
  QQ_INTENTS,
  SANDBOX_API_BASE_URL,
} from "./constants.js";
export { QQFormatConverter } from "./format-converter.js";
export { isQQMentioned } from "./mentions.js";
export type {
  QQAccessTokenResponse,
  QQAdapterBaseConfig,
  QQAdapterConfig,
  QQAdapterMode,
  QQApiHost,
  QQActionEventDataMap,
  QQActionEventType,
  QQApproveGroupJoinRequestOptions,
  QQArkData,
  QQArkKeyValue,
  QQArkObject,
  QQArkObjectKeyValue,
  QQArkPayload,
  QQCreateGroupJoinApprovalStrategyRequest,
  QQCreateGroupJoinApprovalStrategyResponse,
  QQGatewayBotResponse,
  QQGatewayLifecycleEventType,
  QQGroupJoinApplySource,
  QQGroupJoinApprovalEnable,
  QQGroupJoinApprovalGroupOp,
  QQGroupJoinApprovalStrategy,
  QQGroupJoinApprovalStrategyGroupAction,
  QQGroupJoinApprovalStrategyList,
  QQGroupJoinApprovalWhitelistOp,
  QQGroupJoinRequest,
  QQGroupJoinRequestApprovalOp,
  QQGroupJoinRequestAutoApproved,
  QQGroupJoinRequestEventData,
  QQGroupJoinRequestList,
  QQGroupJoinRequestReviewQA,
  QQGroupJoinRequestVerifyInfo,
  QQGroupJoinVerifyMethod,
  QQGroupListQuery,
  QQGroupMuteGlobalRule,
  QQGroupMuteMemberOp,
  QQGroupMuteMemberOpType,
  QQGroupMuteMode,
  QQGroupMuteRecurringRule,
  QQGroupMuteScheduleRule,
  QQGroupMuteSetting,
  QQGroupMutedMember,
  QQIncomingMessage,
  QQKnownDispatchEventType,
  QQMessageEventDataMap,
  QQMessageAttachment,
  QQMessageAuditEventData,
  QQMessageEventType,
  QQMessageMention,
  QQMessageReference,
  QQMediaPayload,
  QQMediaUploadRequest,
  QQMediaUploadResponse,
  QQUploadConfig,
  QQUploadPart,
  QQUploadPartFinishRequest,
  QQUploadPrepareRequest,
  QQUploadPrepareResponse,
  QQPlatformEvent,
  QQPlatformEventDataMap,
  QQPlatformEventHandler,
  QQPlatformEventType,
  QQRawMessage,
  QQSendMessageRequest,
  QQSendMessageOptions,
  QQSentMessage,
  QQSetGroupMemberMuteRequest,
  QQSocketModeAdapterConfig,
  QQSocketModeMessageData,
  QQSocketModeOptions,
  QQSocketModeWebSocket,
  QQSocketModeWebSocketFactory,
  QQStreamMessageRequest,
  QQStreamMessageResponse,
  QQThreadResolvableEventData,
  QQThreadId,
  QQThreadType,
  QQUpdateGroupJoinApprovalStrategyRequest,
  QQUpdateGroupJoinApprovalStrategyResponse,
  QQUpdateGroupJoinApprovalWhitelistRequest,
  QQUpdateGroupJoinApprovalWhitelistResponse,
  QQWebhookAdapterConfig,
  QQWebhookPayload,
  QQWebhookValidationData,
} from "./types.js";

import type { QQAdapterConfig } from "./types.js";
import { QQAdapter } from "./adapter.js";

/**
 * Create a QQ adapter instance for Chat SDK.
 *
 * @param config QQ adapter runtime configuration.
 */
export function createQQAdapter(config: QQAdapterConfig): QQAdapter {
  return new QQAdapter(config);
}
